<?php

namespace UserBundle\Repository;

/**
 * BoostPanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoostPanRepository extends \Doctrine\ORM\EntityRepository
{
}
