<?php

namespace UserBundle\Repository;

/**
 * BoostPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoostPostRepository extends \Doctrine\ORM\EntityRepository
{
}
