<?php

namespace UserBundle\Repository;

/**
 * ComplaintReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
