<?php

namespace UserBundle\Repository;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{
}
