<?php

namespace UserBundle\Repository;

/**
 * GroupPostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPostLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
