<?php

namespace UserBundle\Repository;

/**
 * GroupPostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPostCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
