<?php

namespace UserBundle\Repository;

/**
 * GroupJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupJoinRepository extends \Doctrine\ORM\EntityRepository
{
}
