<?php

namespace UserBundle\Repository;

/**
 * GroupRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
