<?php

namespace UserBundle\Repository;

/**
 * GroupPostImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPostImageRepository extends \Doctrine\ORM\EntityRepository
{
}
