<?php

namespace UserBundle\Repository;

/**
 * GroupPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPostRepository extends \Doctrine\ORM\EntityRepository
{
}
