<?php

namespace UserBundle\Repository;

/**
 * ObjectShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectShareRepository extends \Doctrine\ORM\EntityRepository
{
}
