<?php

namespace UserBundle\Repository;

/**
 * PanLastViewedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanLastViewedRepository extends \Doctrine\ORM\EntityRepository
{
}
