<?php

namespace UserBundle\Repository;

/**
 * PanReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
