<?php

namespace UserBundle\Repository;

/**
 * PanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanRepository extends \Doctrine\ORM\EntityRepository
{
}
