<?php

namespace UserBundle\Repository;

/**
 * PanShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanShareRepository extends \Doctrine\ORM\EntityRepository
{
}
