<?php

namespace UserBundle\Repository;

/**
 * PostShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostShareRepository extends \Doctrine\ORM\EntityRepository
{
}
